---
name: runson

on:
  push:
jobs:

  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
        owner=$(echo '${{ github.repository_owner }}')
        if [ "$owner" == "Fractal-Based-Lifeforms" ]; then
          matrix='[{"runs_on":"ubuntu-latest"}]'
        else
          matrix='[{"runs_on":["self-hosted", "linux", "x64", "v2-build"]}]'
        fi
        echo ::set-output name=matrix::{\"include\":$(echo $matrix)}
  build-n-test:
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    steps:
    - name: Do stuff
      run: echo "Hello foo"
